### ISSUE TITLE
"yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null

### ISSUE THREAD

**Issue by wujekbobixon** [Reascer/WeaponsOfMinecraft-1.18.2#125]
# 1.20.1
# WeaponsOfMiracles-20.1.7.39.jar
 I just want to tell my friend that this weapon (uchigatana )kicks you out of the server and now I discovered that double jumping after leaving the server and entering about 5 minutes later also throws you out of the server. Only then restarting Minecraft helps with this double jumps 
Error:
```
[19:01:29]` [Server thread/ERROR] inecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@5de70206, suppressing error
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null
   at yesman.epicfight.skill.BattojutsuPassive.onReset(BattojutsuPassive.java:45) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
   at yesman.epicfight.skill.BattojutsuPassive.lambda$onInitiate$1(BattojutsuPassive.java:30) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
   at yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
   at yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
   at yesman.epicfight.events.PlayerEvents.rightClickItemServerEvent(PlayerEvents.java:60) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
   at yesman.epicfight.events.__PlayerEvents_rightClickItemServerEvent_RightClickItem.invoke(.dynamic) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:eventbus:B}
   at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
   at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
   at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
   at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:771) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
   at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:282) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinServerPlayerInteractionManager,pl:mixin:A}
   at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:A}
   at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
   at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
   at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
   at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,re:mixin,re:classloading}
   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
   at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
   at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
   at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
[19:01:35] [Server thread/INFO] inecraft/ServerGamePacketListenerImpl]: wujekbobixon lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataKey.readFromBuffer(io.netty.buffer.ByteBuf)" because the return value of "yesman.epicfight.skill.SkillDataKey.byId(int)" is null
[19:01:35] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon left the game
[19:01:43] [Server thread/INFO] inecraft/PlayerList]: wujekbobixon[] logged in with entity id 3624 at (1811.1480150020448, 77.1212968405392, 2406.884291292329)
[19:01:43] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon joined the game
[19:01:43] [Server thread/INFO] [spawnermod/]: Sending config to player.
[19:01:46] [Server thread/INFO] inecraft/ServerGamePacketListenerImpl]: wujekbobixon lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataKey.readFromBuffer(io.netty.buffer.ByteBuf)" because the return value of "yesman.epicfight.skill.SkillDataKey.byId(int)" is null
```
The new Epic Fight version some change with this weapon shall you fix that? 

[I trying to fix that problem with team Epic Fight and it is connected with your mod. ](https://github.com/Yesssssman/epicfightmod/issues/1566)

# Take Care Bro

**Comment by Kapdar** [comment]
+1. Installed latest update from epic fight and updated WOM. Now my dedicated server kicks everyone who uses double jump or katana weapon type. After that the only way to enter the server is through restarting the server.

**Comment by SergenteEnrico** [comment]
This seems to have been a problem for the 20.1.7.39 version of the mod. I have been having this problem with the Uchigatana, the draw attack specifically. Whenever i waited to draw, it crashed and showed the null message to me.

Try moving to 20.1.7.40 seems to have fixed the issue for now.

**Comment by wujekbobixon** [comment]
> This seems to have been a problem for the 20.1.7.39 version of the mod. I have been having this problem with the Uchigatana, the draw attack specifically. Whenever i waited to draw, it crashed and showed the null message to me.
> 
> Try moving to 20.1.7.40 seems to have fixed the issue for now.

I did it yesterday, and that fixed it
