### ISSUE TITLE
unsure if its a mod in compatibility or a bug

### ISSUE THREAD

**Issue by DaleHat** [Reascer/WeaponsOfMinecraft-1.18.2#69]
Suspected Mods: 
Epic Fight (epicfight), Version: 20.6.2
		at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.skill.SkillDataManager$ValueType$BooleanType.writeToBuffer(SkillDataManager.java:202)

	Weapons of Minecraft (wom), Version: 20.1.7.35
		at TRANSFORMER/wom@20.1.7.35/reascer.wom.skill.weaponinnate.DemonicAscensionSkill.cancelOnServer(DemonicAscensionSkill.java:359)

Error Log:
https://pastebin.com/LrQRQehL

here are some bits from the main log that I thought might be helpful.
---------------------

[07Dec2023 21:59:56.027] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.lang.Boolean.booleanValue()" because "data" is null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class de.srendi.advancedperipherals.common.events.Events onEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		2: ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onLivingEquipmentChangeEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		3: ASM: class yesman.epicfight.events.EntityEvents equipChangeEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		4: ASM: me.desht.pneumaticcraft.common.event.MiscEventHandler@3be04717 onEquipmentChanged(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		5: ASM: class com.hollingsworth.arsnouveau.common.event.PerkEvents equipmentChangedEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		6: ASM: class twilightforest.events.MiscEvents armorChanged(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		7: ASM: class com.simibubi.create.content.equipment.armor.NetheriteDivingHandler onLivingEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		8: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@2a06f479 onLivingEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		9: ASM: mob_grinding_utils.events.ChickenFuseEvent@3d897fc3 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		10: ASM: com.talhanation.recruits.PillagerEvents@a263e95 raidStartOnBurningOminous(Lnet/minecraftforge/event/entity/EntityEvent;)V
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "data" is null
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.skill.SkillDataManager$ValueType$BooleanType.writeToBuffer(SkillDataManager.java:202)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.network.server.SPModifySkillData.toBytes(SPModifySkillData.java:44)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112)
	at TRANSFORMER/forge@47.2.16/net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.network.EpicFightNetworkManager.sendToClient(EpicFightNetworkManager.java:53)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.network.EpicFightNetworkManager.sendToPlayer(EpicFightNetworkManager.java:65)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.skill.SkillDataManager.syncData(SkillDataManager.java:97)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.skill.SkillDataManager.setDataSync(SkillDataManager.java:82)
	at TRANSFORMER/wom@20.1.7.35/reascer.wom.skill.weaponinnate.DemonicAscensionSkill.cancelOnServer(DemonicAscensionSkill.java:359)
	at TRANSFORMER/wom@20.1.7.35/reascer.wom.skill.weaponinnate.DemonicAscensionSkill.onRemoved(DemonicAscensionSkill.java:320)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.skill.SkillContainer.setSkill(SkillContainer.java:58)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.world.capabilities.item.CapabilityItem.changeWeaponInnateSkill(CapabilityItem.java:195)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.updateHeldItem(ServerPlayerPatch.java:134)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:490)
	at TRANSFORMER/epicfight@20.6.2/yesman.epicfight.events.__EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21319_(LivingEntity.java:2410)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21315_(LivingEntity.java:2381)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2287)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:842)

[07Dec2023 21:59:56.297] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:145) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "data" is null
	at yesman.epicfight.skill.SkillDataManager$ValueType$BooleanType.writeToBuffer(SkillDataManager.java:202) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.network.server.SPModifySkillData.toBytes(SPModifySkillData.java:44) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.20.1-47.2.16-universal.jar%231085!/:?]
	at yesman.epicfight.network.EpicFightNetworkManager.sendToClient(EpicFightNetworkManager.java:53) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.network.EpicFightNetworkManager.sendToPlayer(EpicFightNetworkManager.java:65) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.skill.SkillDataManager.syncData(SkillDataManager.java:97) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.skill.SkillDataManager.setDataSync(SkillDataManager.java:82) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at reascer.wom.skill.weaponinnate.DemonicAscensionSkill.cancelOnServer(DemonicAscensionSkill.java:359) ~[WeaponsOfMiracles-20.1.7.35.jar%231057!/:20.1.7.35]
	at reascer.wom.skill.weaponinnate.DemonicAscensionSkill.onRemoved(DemonicAscensionSkill.java:320) ~[WeaponsOfMiracles-20.1.7.35.jar%231057!/:20.1.7.35]
	at yesman.epicfight.skill.SkillContainer.setSkill(SkillContainer.java:58) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.world.capabilities.item.CapabilityItem.changeWeaponInnateSkill(CapabilityItem.java:195) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.updateHeldItem(ServerPlayerPatch.java:134) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:490) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at yesman.epicfight.events.__EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic) ~[EpicFight-20.6.2.jar%23773!/:20.6.2]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.world.entity.LivingEntity.m_21319_(LivingEntity.java:2410) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.world.entity.LivingEntity.m_21315_(LivingEntity.java:2381) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2287) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%231080!/:?]
	... 6 more

**Comment by cyraxan** [comment]
try 20.1.7.34 version, latest not working with my mod-pack too
