### ISSUE TITLE
the Wom problem , wats that?

### ISSUE THREAD

**Issue by IcedFireFox** [Reascer/WeaponsOfMinecraft-1.18.2#75]
here the error its in 1.20.1 btw
-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
-- MOD wom --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: yesman/epicfight/world/damagesource/SourceTag
		at reascer.wom.gameasset.WOMSkills.registerSkills(WOMSkills.java:212) ~[WeaponsOfMiracles-20.1.7.35.jar%23239!/:20.1.7.35] {re:classloading}
		at reascer.wom.main.WeaponsOfMinecraft.<init>(WeaponsOfMinecraft.java:58) ~[WeaponsOfMiracles-20.1.7.35.jar%23239!/:20.1.7.35] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.16.jar%23242!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.16.jar%23241!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/crisa/curseforge/minecraft/Instances/escolinha/mods/WeaponsOfMiracles-20.1.7.35.jar
	Failure message: Weapons of Minecraft (wom) has failed to load correctly
		java.lang.NoClassDefFoundError: yesman/epicfight/world/damagesource/SourceTag
	Mod Version: 20.1.7.35
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: yesman.epicfight.world.damagesource.SourceTag
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at reascer.wom.gameasset.WOMSkills.registerSkills(WOMSkills.java:212) ~[WeaponsOfMiracles-20.1.7.35.jar%23239!/:20.1.7.35] {re:classloading}
	at reascer.wom.main.WeaponsOfMinecraft.<init>(WeaponsOfMinecraft.java:58) ~[WeaponsOfMiracles-20.1.7.35.jar%23239!/:20.1.7.35] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.16.jar%23242!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.16.jar%23241!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
wat am i supose to do ?

**Comment by Ap4uuk** [comment]
+1 I also have a similar error
